blank_issues_enabled: true
contact_links:
  - name: Email Support
    url: mailto:alex.rudaev@outlook.com
    about: Please email us if you have any questions or need direct support.
  - name: LinkedIn
    url: https://www.linkedin.com/in/arudaev/
    about: Follow for updates and reach out for quick questions.
